# Generated by Django 4.2.4 on 2024-06-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productsize_productcolor_alter_product_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
