# Generated by Django 4.2.4 on 2024-06-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_color_size_productsize_productcolor_product_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
