# Generated by Django 4.2.4 on 2024-06-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_colors_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
